naccsweb/core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

naccsweb/naccsweb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

from users.forms import CustomAuthenticationForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'login/$', auth_views.LoginView.as_view(redirect_authenticated_user=True, authentication_form=CustomAuthenticationForm), name='login'),
    url(r'', include('core.urls')),
    url(r'', include('users.urls')),
    url(r'', include('django.contrib.auth.urls')),
    url(r'settings/', include('settings.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

naccsweb/settings/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('verify/<slug:uidb64>/<slug:token>)/', views.verify, name='verify'),
    path(r'account/pending', views.pending, name='pending'),
    path(r'account', views.account, name='account'),
    path(r'account/faceitconfirm', views.faceit, name='faceitconfirm'),
    path(r'account/discordcallback', views.discord, name='discord'),
    path(r'account/application', views.application, name="application"),
    path(r'account/application/graduate', views.grad_application, name="grad_application"),
    path(r'account/application/highschool', views.highschool_application, name="highschool_application")
]

naccsweb/settings/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class GraduateFormModel(models.Model):
    class Meta:
        verbose_name = "Graduated Student Application"
        verbose_name_plural = "Graduated Student Applications"

    def __str__(self):
        return self.user.profile.nickname

    user       = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    college    = models.CharField(max_length=80, blank=True)
    grad_date  = models.DateField(null=True, blank=True)
    proof      = models.FileField(upload_to="graduate/proof/")
    other      = models.TextField(max_length=500, blank=True)

class HighSchoolFormModel(models.Model):
    class Meta:
        verbose_name = "High School Student Application"
        verbose_name_plural = "High School Student Applications"
    
    def __str__(self):
        return self.user.profile.nickname

    user       = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    highschool = models.CharField(max_length=80, blank=True)
    college    = models.CharField(max_length=80, blank=True)
    grad_date  = models.DateField(null=True, blank=True)
    proof      = models.FileField(upload_to="highschool/proof/")
    other      = models.TextField(max_length=500, blank=True)

naccsweb/settings/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import GraduateFormModel, HighSchoolFormModel
from .schools import get_schools

class CollegeForm(forms.Form):
    def __init__(self,*args,**kwargs):
        self.schools = kwargs.pop('schools')
        schools_tuple = []
        for school in sorted(self.schools):
            schools_tuple.append((school, school))
        super().__init__(*args, **kwargs)
        self.fields['college'].widget = forms.Select(choices=schools_tuple)

    def clean(self):
        cleaned_data = super().clean()

        email_suffix = cleaned_data.get('email').split('@')[1]
        valid_emails = self.schools.get(cleaned_data.get('college'))
        valid = False
        for email in valid_emails:
            if email_suffix.endswith(email):
                valid = True
                break

        if not valid:
            raise ValidationError('Invalid College Email')

        return cleaned_data    

    college = forms.CharField(label="College Name")
    email   = forms.EmailField(label="College Email")

class GraduateForm(forms.ModelForm):
    class Meta:
        model = GraduateFormModel
        fields = ('college', 'grad_date', 'proof', 'other')
        exclude = ['user']

    college    = forms.CharField(label="College")
    grad_date       = forms.DateField(input_formats=['%m/%d/%Y'])
    proof      = forms.FileField(label="Proof, such as transcript or diploma")
    other      = forms.CharField(label="Other Information", help_text="Optional", widget=forms.Textarea(attrs={'rows': 5}), required=False)

class HighSchoolForm(forms.ModelForm):
    class Meta:
        model = HighSchoolFormModel
        fields = ('highschool', 'college', 'grad_date', 'proof', 'other')
        exclude = ['user']

    highschool = forms.CharField(label="Current Highschool")
    grad_date       = forms.DateField(input_formats=['%m/%d/%Y'])
    college    = forms.CharField(label="Future College")
    proof      = forms.FileField(label="Acceptance Letter")
    other      = forms.CharField(label="Other Information", help_text="Optional", widget=forms.Textarea(attrs={'rows': 5, 'cols': 40}), required=False)

class MilitaryForm(forms.Form):
    # TODO
    pass

naccsweb/settings/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode

from .oauth import get_discord_name, get_faceit_name
from .schools import get_schools
from .forms import CollegeForm, GraduateForm, HighSchoolForm
from .email import email_college_confirmation, check_token
from .models import GraduateFormModel, HighSchoolFormModel

def verify(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and check_token(user, token):
        user.profile.verified_student = True
        user.save()
        return redirect('account')
    else:
        return render(request, 'verification/verification_invalid.html')

@login_required
def account(request):
    try:
        schools = get_schools()
    except:
        schools = []

    if request.method == 'POST':
        # Check if resend was hit
        if ('resend' in request.POST):
            user = User.objects.get(username=request.user.username)
            email_college_confirmation(user.profile.college_email, request)
            return redirect('pending')
            
        form = CollegeForm(request.POST, schools=schools)

        if form.is_valid():
            college = form.cleaned_data['college']
            email = form.cleaned_data['email']

            user = User.objects.get(username=request.user.username)
            user.profile.college_email = email
            user.profile.college = college
            user.save()

            email_college_confirmation(email, request)
            return redirect('pending')
    else:
        form = CollegeForm(schools=schools)
    

    return render(request, 'settings/account.html', {'form': form})

@login_required
def pending(request):
    print (request.user.profile.verified_student)
    if request.user.profile.verified_student:
        return redirect('/')
    return render(request, 'verification/verification_pending.html') 

@login_required
def faceit(request):
    faceit_code = request.GET.get('code')

    if (faceit_code == None):
        return redirect('account')

    faceit_username = get_faceit_name(faceit_code)

    # Enter faceit name into user profile
    user = User.objects.get(username=request.user.username)
    user.profile.faceit = faceit_username
    user.save()

    return redirect('account')
    
@login_required
def discord(request):
    discord_code = request.GET.get('code')

    if (discord_code == None):
        return redirect('account')

    discord_name = get_discord_name(discord_code)

    # Enter discord name into user profile
    user = User.objects.get(username=request.user.username)
    user.profile.discord = discord_name
    user.save()
    return redirect('account')

@login_required
def application(request):
    return render(request, 'settings/base_application.html')

@login_required
def grad_application(request):
    if GraduateFormModel.objects.filter(user=request.user).exists():
        return redirect('account')

    if request.method == "POST":
        form = GraduateForm(request.POST, request.FILES)
        if form.is_valid():
            answers = form.save(commit=False)
            answers.user = User.objects.get(username=request.user.username)
            answers.save()
            return redirect('account')
        else:
            return render(request, 'settings/application.html', {'form': form, 'type': "GRADUATED STUDENT"})
            
    form = GraduateForm()
    
    return render(request, 'settings/application.html', {'form': form, 'type': "GRADUATED STUDENT"})

@login_required
def highschool_application(request):
    if HighSchoolFormModel.objects.filter(user=request.user).exists():
        return redirect('account')

    if request.method == "POST":
        form = HighSchoolForm(request.POST, request.FILES)
        if form.is_valid():
            answers = form.save(commit=False)
            answers.user = User.objects.get(user=request.user)
            answers.save()
            return redirect('account')
        else:
            return render(request, 'settings/application.html', {'form': form, 'type': "HIGH SCHOOL STUDENT"})

    form = HighSchoolForm()

    return render(request, 'settings/application.html', {'form': form, 'type': "HIGH SCHOOL STUDENT"})

naccsweb/settings/templates/settings/account.html
{% extends 'core/base.html' %}

{% block title %}Account Settings{% endblock %}

{% block jumbo_title %}ACCOUNT SETTINGS{% endblock %}

{% block content %}
<div class="content">
    <section id="account_settings">
        <section id="main">
            <section class="panel">
                    <h1 class="title">Personal Info</h1>
                    <div class="underline"></div>
                    <p>Email: {{ user.email }}</p>
                    <p>Bio: {{ user.profile.bio }}</p>
                </section>
            
                <section class="panel">
                    <h1 class="title">College Info</h1>
                    <div class="underline"></div>
                    {% if user.profile.college %}
                    <p>{{ user.profile.college }}</p>
                    {{ user.profile.college_email }}
                    {% if not user.profile.verified_student %}
                    <i class="fa fa-times-circle"></i> <form action="" method="post">{% csrf_token %}<input class="ghost_button" type="submit" name="resend" value="Resend"></form>
                    {% else %}
                    <i class="fa fa-check-circle"></i>
                    {% endif %}
                    {% else %}
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input class="ghost_button" type="submit" name="college_info" value="Save">
                        <a class="not_college_button" href="account/application">Not a current student?</a>
                    </form>
                    {% endif %}
                </section>
        </section>
        <section id="sidebar">
                <section class="panel">
                    <h1 class="title">FACEIT</h1>
                    <div class="underline"></div>
                    {% if user.profile.faceit != "" %}
                    <p>Username: {{ user.profile.faceit }}</p>
                    <a href="#" class="button Faceit" onclick="FACEIT.loginWithFaceit()">Refresh</a>
                    {% else %}
                    <a href="#" class="button Faceit" onclick="FACEIT.loginWithFaceit()">Login With Faceit</a>
                    {% endif %}
                </section>
                <section class="panel">
                    <h1 class="title">Discord</h1>
                    <div class="underline"></div>
                    {% if user.profile.discord != "" %}
                    <p>Username: {{ user.profile.discord }}</p>
                    <a href='https://discordapp.com/api/oauth2/authorize?client_id=610627028479246338&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Fsettings%2Faccount%2Fdiscordcallback&response_type=code&scope=identify'>Refresh</a>
                    {% else %}
                    <a href='https://discordapp.com/api/oauth2/authorize?client_id=610627028479246338&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Fsettings%2Faccount%2Fdiscordcallback&response_type=code&scope=identify'>Login with Discord</a>
                    {% endif %}
                </section>
        </section>
    </section>

</div>
<script src="https://cdn.faceit.com/oauth/faceit-oauth-sdk-1.2.7.min.js" type="text/javascript"></script>
<script type="text/javascript">
    var initParams = {
        client_id: '4c53be11-4f4a-4f71-845a-7a094004f4a0',
        response_type: 'code',
        redirect_popup: false,
        debug: true
    };
    FACEIT.init(initParams);
</script>

{% endblock %}

naccsweb/settings/templates/settings/application.html
{% extends 'settings/base_application.html' %}

{% block title %}Application{% endblock %}

{% block jumbo_title %}{{ type }} APPLICATION{% endblock %}

{% block application %}
<!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- Fengyuan Chen's Datepicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
</head>
<body>
<section class="panel">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}


    </form>
    <script>
  $(function () {
    $("#id_grad_date").datepicker({
      format:'mm/dd/yyyy',
    });
  });
</script>
</section>
{% endblock %}

naccsweb/settings/templates/settings/base_application.html
{% extends 'core/base.html' %}

{% block title %}Application{% endblock %}

{% block jumbo_title %}{{ type }} APPLICATION{% endblock %}

{% block content %}
<div class="content">
    <section class="panel">
        <h1 class="title">Not a current college student?</h1>
        <div class="underline"></div>
        <p>That's fine! We accept players who are entering college, or have graduated from college.</p>
        <p>Select one of the options below that best suit your situation to a form that we will review.</p>
        {% block selector %}
        <div class="selector">
            <a class="option ghost_button" href="/settings/account/application/highschool">I'm in High School</a>
            <a class="option ghost_button" href="/settings/account/application/graduate">I've already graduated</a>
        </div>
        {% endblock %}
        {% block application %}
        
        {% endblock %}
    </section>
</div>

{% endblock %}